### ISSUE TITLE
Extension Commands Not Working

### ISSUE THREAD

**Issue by Srijan1214** [ailisp/commonlisp-vscode#4]
Hello,

I really do think that this will be a helpful extension. I have installed Roswell and added the ~/.roswell/bin to my $PATH.
Currently, I get command not found errors whenever I try to run any commands.

For Example
"Command 'Lisp: Compile And Load File' resulted in an error (command 'lisp.compileAndLoadFile' not found)".

![lisp_error](https://user-images.githubusercontent.com/25398686/88687543-66802e80-d0c6-11ea-89ec-a06a0ac93984.gif)

Also, the autocomplete is not working.

**Comment by ailisp** [comment]
Hi @Srijan1214 , sorry somehow i didn't get email notification. I just tried and it still works to me, so does autocompletion. are you able to run other commonlisp-vscode commands, such as `lisp repl start`?

**Comment by ailisp** [comment]
Btw you're in Rampo College at Mahwah NJ? I used to intern there :) a very beautiful town.

**Comment by Srijan1214** [comment]
@ailisp I think I did something wrong with the installation. The `lisp repl start` command does not work for me.
![lisp_error_2](https://user-images.githubusercontent.com/25398686/90193832-c7c92280-dd93-11ea-9a2f-e8c074296387.gif)

Yes, I am at Ramapo College at Mahwah NJ. Really awesome that you've worked at Mahwah!

**Comment by ailisp** [comment]
There's a possibility your vscode version is old. Can you see:
- What is your vscode version?
- Can you run `cl-lsp` from shell?

**Comment by Srijan1214** [comment]
My vscode version is 1.47.3.

Yes `cl-lsp` does work from the terminal.

**Comment by Srijan1214** [comment]
> My vscode version is 1.47.3.
> 
> Yes `cl-lsp` does work from the terminal.

I set the path as stated using the .bashrc. Maybe this is the issue. I'm new to linux, so I was assuming that the path set in bash should've transferred to Vscode.

**Comment by ailisp** [comment]
1.47 is a new version and it works to me
> I set the path as stated using the .bashrc. Maybe this is the issue. I'm new to linux, so I was assuming that the path set in bash should've transferred to Vscode.

That might be the issue sorry this isn't very user friendly, at least two other people encountered this issue but the error was not yours.
Try set path in `~/.profile` and re-login, because setting in ~/.bashrc didn't pickup by GUI applications. Or, set this to absolute path of cl-lsp:
![image](https://user-images.githubusercontent.com/13259400/90596337-9ab9ad00-e1a3-11ea-9573-8628896bdc82.png)

I also published a new version that use `~/.roswell/bin/cl-lsp` as default

**Comment by smashedtoatoms** [comment]
You might also try opening code from the terminal. Sometimes my zsh path doesn't make it into code, and I have to open it via the terminal to make it behave.

**Comment by Srijan1214** [comment]
Sorry for the very late reply.

I just cannot seem to get this to work. Even after adding the path to .profile or running `code` from the terminal, the error is still persistent.

![image](https://user-images.githubusercontent.com/25398686/91666644-77a8ca80-eacc-11ea-9c5e-731f4f2e4142.png)
I also tried adding the full path, but it didn't work.

**Comment by ailisp** [comment]
The error seems to be the vscode plugin side (commonlisp-vscode), vscode
can find cl-lsp, and cl-lsp alone works on you machine but vscode cannot
find any command registered by commonlisp-vscode. Do you have other lisp
plugin installed, maybe there's conflicting?

**Comment by Srijan1214** [comment]
@smashedtoatoms and @ailisp. Thank you for helping me out. I started to learn slime as recommended by most people. I have tried different things but tinkering around with vscode did not help me. I also do not have any other plugin for lisp in vscode.
 Right now I cannot find the time to look further into this and just need to get on with lisp. So I am closing this issue.
 Please do not be discouraged as I am sure this is occurring because I am a novice with Linux. I will spend more time on this in the future as working on lisp inside vscode is more appealing for me than having to learn something like emacs.

Continue with the great work!

**Comment by smashedtoatoms** [comment]
@Srijan1214 I have one more thing for you to try if you have time.  Open up the project via the cli.  For example, if you have `~/example/test.lisp` try:
- `cd ~/example`
- run `code .`
- In vscode, open the command palette and choose `Lisp: REPL - start`. That seems to work consistently for me on both mac and linux.

Once the repl is running, it should behave.

**Comment by PF4Public** [comment]
Could it be, that `cl-lsp` is not allowed to be run as a shell?

This makes it work for me:
```js
        return vscode.window.createTerminal({
            name: "Common Lisp REPL",
            shellPath: "bash",
            shellArgs: ["-c", "~/.roswell/bin/cl-lsp", "tcp", lspPort.toString()],
            hideFromUser: true,
        });
```

**Comment by ailisp** [comment]
@PF4Public 's change works, the bug was `~` isn't expand to home dir in nodejs (vscode plugin's environment). It's fixed in 0.3.2 so you'll not need to do @PF4Public's hack now

**Comment by PF4Public** [comment]
@ailisp It is now starting the Language Server, but sometimes (at least at the first run and under heavy load) sbcl takes more than a second to start, so the extension fails with a timeout trying to connect to it. I set 60 seconds and now all is fine:
```js
                    setTimeout(() => {
                        reject(new Error("Connection to lsp times out"));
                    }, 60000);
```
60 seconds is probably an overkill though, please raise this timeout to 30 seconds or so… or 10…
